### ISSUE TITLE
UDP Hello World Server is getting stuck

### ISSUE THREAD

**Issue by kiranpradeep** [TommyStarK/Hermes#4]
Thanks for the super easy API. 

Operating System: Ubuntu 16.04 LTS ( also on macOS 10.12.3 )
Compiler: gcc 5.4.0. 
UDP Server: example hello world using Hermes[[1](https://github.com/TommyStarK/Hermes/blob/master/docs/UDP_SERVER.md#example-hello-world)]
UDP Client: Below provided python sample

Issue: I see the UDP server getting stuck/blocked with in 10 seconds.

```
import socket

IP_PORT = ("127.0.0.1", 27017)
MESSAGE1 = '$' * 1024

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

while(True):
        sock.sendto( MESSAGE1, IP_PORT )
```

In example server, I suspected buffer.data() and commented out std::cout line. Still the issue persists.

**Comment by TommyStarK** [comment]
Hello @kiranpradeep,

Thank you for your feedback on Hermes. 
Originally, when I started working on Hermes, the main idea was to improve my skills in C++11 and learn how networking works as well as how TCP/UDP protocols work.
However I recently moved to UK for work and I currently do not have the time to look into your reported issue. I am fully aware that Hermes might have bugs and does not work like I would like to.
Normally I'll have more free time in the coming months and I will be please to dig deeper and fix the remaining bugs.
I am truely sorry to not have the time right now to provide a solution to your issue.

As soon as I got the time I'll fix that and run more tests to highlight potential bugs.

ps: If you are looking for an easy to use API to perform TCP operations in C++11, I would recommend  you to use https://github.com/Cylix/tacopie which is a great and maintained library. For UDP protocol, https://github.com/Qihoo360/evpp.

Best,

Thomas

**Comment by TommyStarK** [comment]
@kiranpradeep I tried your python script with the example of the Async UDP server (https://github.com/TommyStarK/Hermes/blob/master/docs/UDP_SERVER.md) and it works perfectly :)

Best,
