### ISSUE TITLE
Multiple definition of hermes::internal::set_io_service(std::shared_ptr<hermes::internal::io_service> const&)

### ISSUE THREAD

**Issue by JesvinJoseph** [TommyStarK/Hermes#9]
Hi,
Compiler gives multiple definition error when "hermes.hpp" included multiple times it the project.

Multiple definition error is for two funcitons, hermes::internal::set_io_service(std::shared_ptr<hermes::internal::io_service> const&)'  **AND**
hermes::internal::get_io_service(int)

Error:-
/tmp/ccJHnjth.o: In function `hermes::internal::set_io_service(std::shared_ptr<hermes::internal::io_service> const&)':
main.cpp:(.text+0x19b): multiple definition of `hermes::internal::set_io_service(std::shared_ptr<hermes::internal::io_service> const&)'
/tmp/ccVlB1UB.o:test.cpp:(.text+0x19b): first defined here
/tmp/ccJHnjth.o: In function `hermes::internal::get_io_service(int)':
main.cpp:(.text+0x1d3): multiple definition of `hermes::internal::get_io_service(int)'
/tmp/ccVlB1UB.o:test.cpp:(.text+0x1d3): first defined here
collect2: error: ld returned 1 exit status

Issue resolved when the closing braces of the namespaces moved from the 865th line to 886 in hermes.hpp.

**Comment by TommyStarK** [comment]
Hi @JesvinJoseph ,

Thank  you so much for reporting this issue :) I'll test and fix this ASAP.

Best,
